# add unit & enable service

  - name: Add unit file for puma
    template:
      src: puma.service.j2
      dest: /etc/systemd/system/puma.service
    notify: reload puma

  - name: Add config for DB connection
    template:
      src: db_config.j2
      dest: "/home/{{ deploy_user }}/db_config"
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"

  - name: Enable puma
    systemd: name=puma enabled=yes
